// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CompanySyncStatus struct {
	CompanyID            *string `json:"companyId,omitempty"`
	DataPushed           *bool   `json:"dataPushed,omitempty"`
	ErrorMessage         *string `json:"errorMessage,omitempty"`
	SyncExceptionMessage *string `json:"syncExceptionMessage,omitempty"`
	SyncID               *string `json:"syncId,omitempty"`
	SyncStatus           *string `json:"syncStatus,omitempty"`
	SyncStatusCode       *int    `json:"syncStatusCode,omitempty"`
	SyncUtc              *string `json:"syncUtc,omitempty"`
}

type GetSyncResult struct {
	Success         bool               `json:"success"`
	CodatStatusCode *int               `json:"codatStatusCode,omitempty"`
	Errors          []*string          `json:"errors,omitempty"`
	Sync            *CompanySyncStatus `json:"sync,omitempty"`
}

type LatestSyncResult struct {
	Success         bool               `json:"success"`
	CodatStatusCode *int               `json:"codatStatusCode,omitempty"`
	Errors          []*string          `json:"errors,omitempty"`
	LatestSync      *CompanySyncStatus `json:"latestSync,omitempty"`
}
